# Generated by Django 5.0.6 on 2024-06-04 07:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('closed', 'Closed')], max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='management_app.project')),
            ],
        ),
    ]
