# Generated by Django 5.0.6 on 2024-06-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Major', 'Major'), ('Critical', 'Critical'), ('Urgent', 'Urgent')], default='Normal', max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('closed', 'Closed')], default='new', max_length=15),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('tasks', models.ManyToManyField(related_name='tags', to='management_app.task')),
            ],
        ),
    ]
