# Generated by Django 5.0.6 on 2024-06-04 17:09

import django.core.validators
import django.db.models.deletion
import management_app.models.task
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0003_projectfile_project_project_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('closed', 'Closed')], default='new', max_length=15)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Major', 'Major'), ('Critical', 'Critical'), ('Urgent', 'Urgent')], default='Normal', max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(default=management_app.models.task.calculate_end_of_month)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='management_app.project')),
                ('tags', models.ManyToManyField(related_name='tasks', to='management_app.tag')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
                'ordering': ['-due_date'],
                'unique_together': {('name', 'project')},
            },
        ),
    ]
