# Generated by Django 5.0.6 on 2024-06-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0005_alter_task_assignee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-name'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
