# Generated by Django 5.0.6 on 2024-06-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0006_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-due_date'], 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'project')},
        ),
    ]
