# Generated by Django 5.0.6 on 2024-06-04 09:39

import management_app.models.task
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0006_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=management_app.models.task.calculate_end_of_month),
        ),
    ]
