# Generated by Django 5.0.6 on 2024-06-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0006_alter_task_due_date'),
        ('management_app', '0007_alter_task_options_alter_task_unique_together'),
        ('management_app', '0007_projectfile_project_project_files'),
    ]

    operations = [
    ]
